#!/usr/bin/env bash
#
# Fetch OpenCodeReview's GitLab MR-comment poster, at a pinned version, with a
# checksum check.
#
# `review/gate.py` already summarises findings in the job log and gates on
# severity. This adds the other half: posting findings as *inline discussions*
# on the merge request, next to the lines they refer to.
#
# That publisher is upstream's `post_review.py` — Apache-2.0, several hundred
# lines of GitLab API handling (pagination, rate limits, retries, sticky
# summaries). Reimplementing it would be pointless and vendoring it would mean
# carrying a copy that silently goes stale. So it is fetched on demand, pinned
# to a release tag, and verified against a recorded sha256 before use.
#
# Usage:
#   ./review/fetch_poster.sh                 # into review/vendor/
#   ./review/fetch_poster.sh --check         # verify an existing copy
#   OCR_POSTER_VERSION=v1.8.9 ./review/fetch_poster.sh
#
# Exit codes:
#   0  fetched (or already present) and checksum verified
#   1  download or checksum failure — nothing is left in place
#   2  usage / missing tooling

set -euo pipefail

# A user's CDPATH makes `cd` print the directory it landed in, which would
# otherwise end up inside the command substitutions below and corrupt every
# path derived from them. Clearing it is local to this script's shell.
CDPATH=''

PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

# Pinned deliberately. Bump both together — a version bump with a stale
# checksum fails closed, which is the point.
VERSION="${OCR_POSTER_VERSION:-v1.8.10}"
SHA256_v1_8_10="84b572dd544cc09ef609b12f1c3e39affdbcf1e8d36761d2106b12497408a59c"

DEST_DIR="review/vendor"
DEST="$DEST_DIR/post_review.py"
URL="https://raw.githubusercontent.com/alibaba/open-code-review/${VERSION}/examples/gitlab_ci/post_review.py"

msg() { printf '[review] %s\n' "$*" >&2; }
die() { printf '[review] error: %s\n' "$1" >&2; exit "${2:-1}"; }

expected_sha() {
    # Only versions whose checksum has been recorded may be fetched. An
    # unpinned version is worse than no publisher: it is arbitrary code from
    # the network running in CI with an API token in scope.
    case "$VERSION" in
        v1.8.10) printf '%s' "$SHA256_v1_8_10" ;;
        *) return 1 ;;
    esac
}

command -v curl >/dev/null 2>&1 || die "curl is required" 2
command -v sha256sum >/dev/null 2>&1 || die "sha256sum is required" 2

if ! want="$(expected_sha)"; then
    die "no recorded checksum for ${VERSION}.
       Record one before using it:
         curl -fsSL '${URL}' | sha256sum
       then add it to review/fetch_poster.sh. Fetching unverified code that
       runs in CI with an API token is not a shortcut worth taking." 2
fi

if [[ "${1:-}" == "--check" ]]; then
    [[ -f "$DEST" ]] || die "no $DEST — run ./review/fetch_poster.sh first"
    have="$(sha256sum "$DEST" | cut -d' ' -f1)"
    [[ "$have" == "$want" ]] || die "checksum mismatch for $DEST
       expected ${want}
       actual   ${have}
       Delete it and re-fetch."
    msg "$DEST matches the pinned ${VERSION} checksum"
    exit 0
fi

if [[ -f "$DEST" ]] && [[ "$(sha256sum "$DEST" | cut -d' ' -f1)" == "$want" ]]; then
    msg "already present and verified: $DEST (${VERSION})"
    exit 0
fi

mkdir -p "$DEST_DIR"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

msg "fetching ${VERSION} publisher…"
curl -fsSL --max-time 60 "$URL" -o "$tmp" || die "download failed: $URL"

have="$(sha256sum "$tmp" | cut -d' ' -f1)"
if [[ "$have" != "$want" ]]; then
    die "checksum mismatch — refusing to install
       expected ${want}
       actual   ${have}
       Either the tag moved or the download was tampered with. Verify before
       updating the recorded checksum."
fi

mv "$tmp" "$DEST"
chmod 0644 "$DEST"
trap - EXIT

cat > "$DEST_DIR/NOTICE" <<EOF
post_review.py
  Source:  https://github.com/alibaba/open-code-review
  Version: ${VERSION}
  License: Apache License 2.0
  SHA-256: ${want}

Fetched by review/fetch_poster.sh. Not part of this project's own source, and
not covered by this project's LICENSE. Redistributed here under the terms of
the Apache License 2.0; see the upstream repository for the full text and
copyright notices.

Do not edit this file — re-fetching overwrites it, and local edits would break
the checksum check.
EOF

msg "installed $DEST (${VERSION}, checksum verified)"
msg "see $DEST_DIR/NOTICE for licensing"
