#!/usr/bin/env python3
"""Refresh the generated region of AGENTS.md for <name>.

`AGENTS.md` has two halves:

  * Between `<!-- scaffold:start -->` and `<!-- scaffold:end -->` are the
    conventions the scaffold generated — security posture, testing contract,
    documentation rules. These are shared across every project and get better
    over time.
  * Everything outside those markers is **yours**: project-specific rules,
    domain notes, team agreements. Nothing here ever touches it.

Without the split, a project that adopts an improved convention has to either
hand-merge it or lose its local rules, so in practice it does neither and the
conventions rot. With the split, upgrading is one command.

Usage:
    python3 scripts/refresh_agents.py --from /path/to/yala-scaffold
    python3 scripts/refresh_agents.py --from ... --check    # CI: fail on drift
    python3 scripts/refresh_agents.py --from ... --diff     # preview

The kit is not vendored into the project, so `--from` must point at a checkout
of the scaffold repository. Nothing is fetched over the network.

Exit codes:
    0  updated, already current, or (with --check) in sync
    1  drift found under --check, or the source template is missing
    2  usage error
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
AGENTS = PROJECT_ROOT / "AGENTS.md"

BLOCK_START = "<!-- scaffold:start -->"
BLOCK_END = "<!-- scaffold:end -->"

# Placeholders the scaffold substitutes when it first generates AGENTS.md.
# Re-applied here so a refreshed block matches what the scaffold would write.
SUBSTITUTIONS = {
    "<name>": "<name>",
    "<shape>": "<shape>",
    "<lang>": "<lang>",
    "<PORT>": "<PORT>",
    "<qa_file>": "<qa_file>",
    "<domain>": "<domain>",
}


def split(text: str) -> tuple[str, str, str] | None:
    """Split into (before, managed_block, after), or None when unmarked."""
    start = text.find(BLOCK_START)
    end = text.find(BLOCK_END)
    if start == -1 or end == -1 or end < start:
        return None
    return text[:start], text[start : end + len(BLOCK_END)], text[end + len(BLOCK_END) :]


def render(kit_root: Path) -> str:
    """Read the kit's AGENTS template and apply this project's placeholders."""
    template = kit_root / "templates" / "AGENTS_TEMPLATE.md"
    if not template.is_file():
        raise SystemExit(
            f"ERROR: no AGENTS template at {template}\n"
            f"       Is --from pointing at an yala-scaffold checkout?"
        )
    text = template.read_text(encoding="utf-8")
    parts = split(text)
    if parts is None:
        raise SystemExit(
            f"ERROR: {template} has no scaffold:start/scaffold:end markers.\n"
            f"       That kit version predates refreshable AGENTS.md."
        )
    block = parts[1]
    for placeholder, value in SUBSTITUTIONS.items():
        block = block.replace(placeholder, value)
    return block


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh the generated region of AGENTS.md")
    parser.add_argument(
        "--from",
        dest="kit_root",
        required=True,
        type=Path,
        help="path to an yala-scaffold checkout",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if out of date, write nothing")
    mode.add_argument("--diff", action="store_true", help="show what would change")
    args = parser.parse_args()

    if not AGENTS.is_file():
        print(f"ERROR: {AGENTS} not found", file=sys.stderr)
        return 2

    current_text = AGENTS.read_text(encoding="utf-8")
    parts = split(current_text)
    if parts is None:
        print(
            f"ERROR: {AGENTS.name} has no scaffold:start/scaffold:end markers.\n"
            f"       It was generated by an older kit version. Add the markers\n"
            f"       around the generated conventions by hand, once, then this\n"
            f"       command will keep them current.",
            file=sys.stderr,
        )
        return 1

    before, current_block, after = parts
    fresh_block = render(args.kit_root)

    if current_block.strip() == fresh_block.strip():
        print("AGENTS.md generated region is up to date")
        return 0

    if args.check:
        print(
            "ERROR: AGENTS.md generated region is out of date.\n"
            "       Run: python3 scripts/refresh_agents.py --from <kit> ",
            file=sys.stderr,
        )
        return 1

    if args.diff:
        diff = difflib.unified_diff(
            current_block.splitlines(keepends=True),
            fresh_block.splitlines(keepends=True),
            fromfile="AGENTS.md (current)",
            tofile="AGENTS.md (kit)",
        )
        sys.stdout.writelines(diff)
        return 0

    AGENTS.write_text(before + fresh_block + after, encoding="utf-8")
    print("AGENTS.md generated region refreshed — your own sections are untouched")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
